import { StayExtension } from '../types';

export function getTodayWindowDates(): { validFrom: string; validUntil: string } {
  const now = new Date();
  const validFrom = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 16, 0, 0, 0);
  const validUntil = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 20, 0, 0, 0);
  return {
    validFrom: validFrom.toISOString(),
    validUntil: validUntil.toISOString(),
  };
}

const { validFrom: todayStart, validUntil: todayEnd } = getTodayWindowDates();

// Yesterday date for expired passes
const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);
const yesterdayStart = new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate(), 16, 0, 0).toISOString();
const yesterdayEnd = new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate(), 20, 0, 0).toISOString();

export const INITIAL_MOCK_PASSES: StayExtension[] = [
  {
    id: 'ext_arjun_001',
    studentId: 'stu_001',
    studentName: 'Arjun Sharma',
    studentEnrollment: 'PU-2024-1001',
    studentYear: '2nd Year (Semester 4)',
    email: 'student@poornima.edu.in',
    department: 'Computer Science & Engineering',
    duration: 4,
    reason: 'Badminton & Gym Session (Evening Complex Pass)',
    amount: 100,
    transactionId: 'TXN-PU-98214532',
    paymentMethod: 'UPI',
    upiApp: 'Google Pay',
    qrCode: JSON.stringify({
      version: '1.0',
      passId: 'ext_arjun_001',
      studentId: 'stu_001',
      studentName: 'Arjun Sharma',
      enrollment: 'PU-2024-1001',
      studentYear: '2nd Year (Semester 4)',
      department: 'Computer Science & Engineering',
      duration: 4,
      transactionId: 'TXN-PU-98214532',
      validFrom: todayStart,
      validUntil: todayEnd,
      createdAt: new Date().toISOString(),
      signature: 'PU-SIG-4532',
    }),
    createdAt: new Date().toISOString(),
    validFrom: todayStart,
    validUntil: todayEnd,
    status: 'valid',
  },
  {
    id: 'PAY-2024-001-JOHN',
    studentId: 'STU-001',
    studentName: 'John Doe',
    studentEnrollment: '2024-COMP-001',
    studentYear: '3rd Semester',
    email: 'john@poornima.edu.in',
    department: 'Computer Engineering',
    duration: 4,
    reason: 'Football Field Turf Practice',
    amount: 100,
    transactionId: 'TXN-12345678',
    paymentMethod: 'Card',
    cardLast4: '4242',
    qrCode: JSON.stringify({
      version: '1.0',
      passId: 'PAY-2024-001-JOHN',
      studentId: 'STU-001',
      studentName: 'John Doe',
      enrollment: '2024-COMP-001',
      department: 'Computer Engineering',
      duration: 4,
      transactionId: 'TXN-12345678',
      validFrom: todayStart,
      validUntil: todayEnd,
      createdAt: new Date().toISOString(),
      signature: 'PU-SIG-5678',
    }),
    createdAt: new Date().toISOString(),
    validFrom: todayStart,
    validUntil: todayEnd,
    status: 'valid',
  },
  {
    id: 'PAY-2024-002-JANE',
    studentId: 'STU-002',
    studentName: 'Jane Smith',
    studentEnrollment: '2024-MECH-045',
    studentYear: '2nd Semester',
    email: 'jane@poornima.edu.in',
    department: 'Mechanical Engineering',
    duration: 4,
    reason: 'Basketball Court & Fitness Center',
    amount: 100,
    transactionId: 'TXN-87654321',
    paymentMethod: 'UPI',
    upiApp: 'PhonePe',
    qrCode: JSON.stringify({
      version: '1.0',
      passId: 'PAY-2024-002-JANE',
      studentId: 'STU-002',
      studentName: 'Jane Smith',
      enrollment: '2024-MECH-045',
      department: 'Mechanical Engineering',
      duration: 4,
      transactionId: 'TXN-87654321',
      validFrom: yesterdayStart,
      validUntil: yesterdayEnd,
      createdAt: yesterdayStart,
      signature: 'PU-SIG-4321',
    }),
    createdAt: yesterdayStart,
    validFrom: yesterdayStart,
    validUntil: yesterdayEnd,
    status: 'expired',
  },
  {
    id: 'PAY-2024-003-MIKE',
    studentId: 'STU-003',
    studentName: 'Mike Johnson',
    studentEnrollment: '2024-ECE-089',
    studentYear: '4th Semester',
    email: 'mike@poornima.edu.in',
    department: 'Electronics & Communication',
    duration: 4,
    reason: 'Cricket Nets & Track Area',
    amount: 100,
    transactionId: 'TXN-55555555',
    paymentMethod: 'Net Banking',
    bank: 'HDFC Bank',
    qrCode: JSON.stringify({
      version: '1.0',
      passId: 'PAY-2024-003-MIKE',
      studentId: 'STU-003',
      studentName: 'Mike Johnson',
      enrollment: '2024-ECE-089',
      department: 'Electronics & Communication',
      duration: 4,
      transactionId: 'TXN-55555555',
      validFrom: todayStart,
      validUntil: todayEnd,
      createdAt: new Date().toISOString(),
      signature: 'PU-SIG-5555',
    }),
    createdAt: new Date().toISOString(),
    validFrom: todayStart,
    validUntil: todayEnd,
    status: 'valid',
  },
  {
    id: 'ext_priya_004',
    studentId: 'stu_004',
    studentName: 'Priya Patel',
    studentEnrollment: 'PU-2023-5521',
    studentYear: '3rd Year (Semester 6)',
    email: 'priya.patel@poornima.edu.in',
    department: 'Civil Engineering',
    duration: 4,
    reason: 'Lawn Tennis Court Practice',
    amount: 100,
    transactionId: 'TXN-PU-11223344',
    paymentMethod: 'UPI',
    upiApp: 'Paytm',
    qrCode: JSON.stringify({
      version: '1.0',
      passId: 'ext_priya_004',
      studentId: 'stu_004',
      studentName: 'Priya Patel',
      enrollment: 'PU-2023-5521',
      department: 'Civil Engineering',
      duration: 4,
      transactionId: 'TXN-PU-11223344',
      validFrom: todayStart,
      validUntil: todayEnd,
      createdAt: new Date().toISOString(),
      signature: 'PU-SIG-3344',
    }),
    createdAt: new Date().toISOString(),
    validFrom: todayStart,
    validUntil: todayEnd,
    status: 'valid',
  }
];
